version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data
    environment:
      - POSTGRES_DB=edu_math
      - POSTGRES_USER=hello 
      - POSTGRES_PASSWORD=1
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    depends_on:
      - db
