# Generated by Django 4.1.6 on 2023-02-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="text",
            new_name="description",
        ),
    ]
