# Generated by Django 4.1.6 on 2023-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_lesson_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="upload",
            field=models.FileField(default="MEDIA", max_length=254, upload_to="media/"),
        ),
    ]
